import { Section } from '../../components/Section';

export const TermsOfService = () => {
    return (
        <div className="min-h-screen bg-cream">
            <Section className="max-w-4xl mx-auto py-32 px-6">
                <div className="mb-16">
                    <span className="text-brandPurple font-bold uppercase tracking-widest text-xs">Legal</span>
                    <h1 className="text-5xl md:text-7xl font-bold mt-6 mb-8">Terms of Service</h1>
                    <p className="text-brandBlack/40 font-medium">Last updated: February 21, 2026</p>
                </div>

                <div className="prose prose-lg max-w-none space-y-12 text-brandBlack/70 font-medium leading-relaxed">
                    <section>
                        <h2 className="text-3xl font-bold text-brandBlack mb-6">1. Acceptance of Terms</h2>
                        <p>
                            By accessing or using StudyLite AI, you agree to be bound by these Terms of Service. If you do not agree to all of these terms, do not use our service.
                        </p>
                    </section>

                    <section>
                        <h2 className="text-3xl font-bold text-brandBlack mb-6">2. Use of Service</h2>
                        <p>
                            StudyLite AI provides an AI-powered study platform. You agree to use the service only for lawful purposes and in accordance with these Terms. You are responsible for maintaining the confidentiality of your account credentials.
                        </p>
                    </section>

                    <section>
                        <h2 className="text-3xl font-bold text-brandBlack mb-6">3. Content and AI</h2>
                        <p>
                            Our platform uses artificial intelligence to process your notes. While we strive for accuracy, AI-generated content may occasionally contain errors. You are responsible for verifying any critical information generated by our service.
                        </p>
                    </section>

                    <section>
                        <h2 className="text-3xl font-bold text-brandBlack mb-6">4. Intellectual Property</h2>
                        <p>
                            The service and its original content, features, and functionality are and will remain the exclusive property of StudyLite AI and its licensors.
                        </p>
                    </section>

                    <section className="pt-12 border-t border-brandBlack/5">
                        <p>If you have any questions about these Terms, please contact us at support@studylite.ai.</p>
                    </section>
                </div>
            </Section>
        </div>
    );
};
